fixed bug in about page
makesmatheasy/makesmatheasy pull request #5221
Opened 2021-06-10 09:18 UTC by AB-san

## Related Issue

- Info about Issue or bug

fix #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

2021-06-10 09:19 UTC, AB-san commented
@sairish2001  I have made some changes due to which the loading time of css is reduced to a much greater extent but there is still some delay.

2021-06-10 09:21 UTC, AB-san commented
@sairish2001 If you have any other way to reduce the delay please let me know

2021-06-12 16:00 UTC, sairish2001 requested changes
```
<div class="collapse card rounded" id="about">
.....
</div>
```
there's a div in the `index.html` page, just remove it, the bug will be resolved no need of changing CSS in `about.html`

2021-06-13 00:29 UTC, AB-san commented
> ```
> <div class="collapse card rounded" id="about">
> .....
> </div>
> ```
> 
> there's a div in the `index.html` page, just remove it, the bug will be resolved no need of changing CSS in `about.html`

@sairish2001  Please review this now , I hv made the requested changes

2021-06-13 05:30 UTC, sairish2001 requested changes

2021-06-13 05:30 UTC, sairish2001 commented on index.html
>              </div>
You missed this </div> to delete

2021-06-13 06:57 UTC, sairish2001 approved these changes

2021-06-13 06:57 UTC, merged

2021-06-13 06:58 UTC, AB-san commented on index.html
>              </div>
Really sorry,
I have rectified it now